name: terraform-provider-kops      # name of the module
build:              # list of build commands to execute in each platform
  linux:
    cmd: ../scripts/build_binaries.sh
properties:
  version: "0.1.0"
