pipeline:
  build-cloudflarectl:
    image: plugins/docker:17.05
    repo: quay.io/honestbee/devops-tools
    dockerfile: ./cloudflarectl/Dockerfile
    context: ./cloudflarectl/
    tags:
      - cloudflarectl
      - cloudflarectl-${DRONE_BRANCH}
      - cloudflarectl-${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}
    registry: quay.io
    email: "devops@honestbee.com"
    secrets: [ docker_username, docker_password ]
    when:
      branch: [ master ]

  notify:
    image: plugins/slack
    channel: feed-devops
    secrets:
      - source: slack_webhook
        target: plugin_webhook
    when:
      status: [ success, failure ]
