pipeline:
  build-cloudflarectl:
    image: plugins/docker:17.05
    repo: quay.io/honestbee/cloudflarectl
    dockerfile: ./cloudflarectl/Dockerfile
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}
      - latest
    registry: quay.io
    email: "devops@honestbee.com"
    secrets: [ docker_username, docker_password ]
    when:
      branch: [ master, 2017-12-25-add-cloudclare-clear-cache-tool ]

  notify:
    image: plugins/slack
    channel: feed-devops
    secrets:
      - source: slack_webhook
        target: plugin_webhook
    when:
      status: [ success, failure ]