workspace:
  base: /go/src

pipeline:
  build:
    image: quay.io/honestbee/monorepo:2018-02-12-add-gox-image
    pull: true
    commands:
      - git rev-parse master~1
      - mbt build diff --from `git rev-parse master~1` --to ${DRONE_COMMIT_SHA}
    when:
      event: tag

  github_release:
    image: plugins/github-release
    repo_owner: honestbee
    repo_name: devops-tools
    secrets: [ github_token ]
    files: bin/*
    when:
      event: tag
