workspace:
  base: /go/src

pipeline:
  build:
    image: quay.io/honestbee/monorepo:2018-02-12-add-gox-image
    pull: true
    commands:
      - git show-ref
      - mbt build diff --from ${DRONE_PREV_COMMIT_SHA} --to ${DRONE_COMMIT_SHA}

  github_release:
    image: plugins/github-release
    build_event: push
    repo_owner: honestbee
    repo_name: devops-tools
    secrets: [ github_token ]
    files: bin/*
