workspace:
  base: /go/src

pipeline:
  build:
    image: quay.io/honestbee/monorepo:2018-02-12-add-gox-image
    pull: true
    commands:
      - mbt build diff --from ee191bea2f96ec7a3c1f70c1cddb9e4781569516 --to e6a303d7349c7c7631fdabd87cc766ec05e01426
    when:
      event: tag

  github_release:
    image: plugins/github-release
    repo_owner: honestbee
    repo_name: devops-tools
    secrets: [ github_token ]
    files: bin/*
    when:
      event: tag
