apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: iperf3-server
  labels:
    name: iperf3-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iperf3-server
  template:
    metadata:
      labels:
        name: iperf3-server
    spec:
      containers:
        - name: iperf3-server
          image: networkstatic/iperf3
          args: ['-s']
          ports:
            - containerPort: 5201
              name: server
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-server
spec:
  selector:
    name: iperf3-server
  ports:
    - protocol: TCP
      port: 5201
      targetPort: server
